# Future Work {.unnumbered}

I plan to explore qualitative analysis tools, such as R-based Qualitative Data Analysis (RQDA), to conduct a more in-depth and nuanced examination of the interviews. While computational tools are useful for providing a general overview of the text, highlighting keywords and generating topic models that suggest possible themes, they often miss context and subtler insights. To capture these nuances, one would need to read through the text in its entirety and assign topic codes to different chunks of text as they appear.

RQDA is a computer-assisted qualitative analysis tool that provides a GUI for systematic human interpretation. Users can assign topic codes, highlight text, and classify content directly within the interface. One of the package’s strengths is that it generates a database in the background, which can be queried to explore the data further, for example, to investigate whether certain themes appear more frequently in different time periods.

Another vision I have for the future is creating a website similar to [The Jamaica Neighborhood Plan’s Voice to Vision](https://v2v-jamaicaplan.ccc-mit.org/), which showcases community feedback from various meetings. The site could present a grid of dialogue shared by interviewees, allowing users to explore the feedback geographically to see which locations are referenced. Users could also filter the dialogue by theme, which is a way to showcase transparency as discussed in the paragraph above. Additionally, visualizations could display the distribution of topics by time period, geography, or demographic variables, providing both a detailed and interactive view of the experiences shared in these oral histories.
